FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    jpegoptim optipng pngquant gifsicle \
    vim \
    git \
    curl \
    zip \
    unzip \
    libpq-dev \
    libzip-dev \
    libexif-dev \
    libonig-dev \

    default-mysql-client \
    # Clean up
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www

RUN docker-php-ext-install pdo pdo_pgsql mbstring zip exif pcntl gd mysqli pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

COPY . /var/www

COPY --chown=www:www . /var/www

RUN chown -R www-data:www-data /var/www/application
RUN chmod -R 777 /var/www/application

USER www

EXPOSE 9000
CMD ["php-fpm"]
